name: Javascript Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 5 * * 5"

permissions: read-all

jobs:
  devskim:
    name: DevSkim
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: devskim-results.sarif

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Prettier
        if: github.event_name != 'pull_request'
        uses: creyD/prettier_action@v4.3

      - name: Run Prettier on changes
        if: github.event_name == 'pull_request'
        uses: creyD/prettier_action@v4.3
        with:
          only_changed: True
