name: Javascript Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 5 * * 5"

permissions: read-all

jobs:
  devskim:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c
        with:
          disable-sudo: true
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: microsoft/DevSkim-Action@4b5047945a44163b94642a1cecc0d93a3f428cc6

      - uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3
        with:
          sarif_file: devskim-results.sarif

  js-standard:
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c
        with:
          disable-sudo: true
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '24'
          check-latest: true

      - run: npm install standard --global

      - run: npm test
